name: Build & Publish (local registry)
on:
  push:
    branches: [ master, main ]
jobs:
  build-publish:
    runs-on: self-hosted
    permissions:
      contents: read
    env:
      IMAGE: 127.0.0.1:5000/discord-stock-bot  # Use container name instead of 127.0.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show Docker info
        run: |
          docker info
          docker buildx ls || true
          echo "Registry check:"
          curl -v 127.0.0.1:5000/v2/ || true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
          config-inline: |
            [registry."127.0.0.1:5000"]
              http = true
              insecure = true
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}